---

dist: 'trusty'

language: 'python'

python:
  - '2.7'

sudo: 'required'

env:
    - PLAYBOOK: test.yml
      ANSIBLE_FORCE_COLOR: True
      ANSIBLE_LOG_PATH: './ansible.log'
      ANSIBLE_ROLES_PATH: '../'
    - PLAYBOOK: test_bgp.yml
      ANSIBLE_FORCE_COLOR: True
      ANSIBLE_LOG_PATH: './ansible.log'
      ANSIBLE_ROLES_PATH: '../'

install:
  #- 'sudo apt-get purge -y mysql-common mysql-server-5.6 mysql-server-core-5.6 mysql-client-5.6 mysql-client-core-5.6'
  #- 'sudo apt-get autoremove -y'
  #- 'sudo rm /var/lib/mysql/debian-5.6.flag'
  # Install test requirements
  - 'pip install -r requirements-devel.txt'
  - |
    if [ -f tests/requirements.yml ]; then
      ansible-galaxy install -r tests/requirements.yml
    fi

script:
  # Check syntax of YAML files.
  - 'yamllint -c .yamllint.conf .'

  # Check syntax of role.
  - 'ansible-playbook -i localhost, -c local tests/${PLAYBOOK} --syntax-check'

  # DEBUG
  - 'ls -l /var/run/mysqld/'

  # Run role.
  - 'ansible-playbook -i localhost, -c local tests/${PLAYBOOK} --diff --verbose'

  # Run role again to check idempotence failure.
  - 'ansible-playbook -i localhost, -c local tests/${PLAYBOOK} --diff --verbose'
  # DEBUG
  - 'ls -l /var/run/mysqld/'
  # Detect idempotence failure.
  - 'tail -n 1 ansible.log | grep -Eq "changed=0 +unreachable=0 +failed=0"'

notifications:
  webhooks: 'https://galaxy.ansible.com/api/v1/notifications/'
