---

- name: Grab edge-router
  command: midonet-cli -e router list | grep '{{ midonet_gateway_edge_router_name }}'
  register: edge_router
  changed_when: False

- name: 

- name: Set router AS number
  command:
  when: '"asn {{ midonet_gateway_bgp_local_as }}" not in edge_router.stdout'

- name: Check BGP Peers
  command: neutron bgp-peer-list
  register: bgp_peer_list
  environment: '{{ keystone_env }}'

- name: Create BGP Peers
  command: >
    neutron bgp-peer-create '{{ item.name }}'
    --peer-ip '{{ item.ip }}'
    --remote-as '{{ item.remote_as }}'
    --auth-type '{{ item.auth_type | default("none") }}'
    --password '{{ item.password | default("") }}'
  with_items: '{{ midonet_gateway_bgp_peers }}'
  when: '"{{ item.name }}" not in bgp_peer_list.stdout'
  environment: '{{ keystone_env }}'

- name: Add BGP Peers to Speaker
  command: >
    neutron bgp-speaker-peer-add
    '{{ midonet_gateway_bgp_speaker_name }}'
    '{{ item.name }}'
  with_items: '{{ midonet_gateway_bgp_peers }}'
  when: '"{{ item.name }}" not in bgp_peer_list.stdout'
  environment: '{{ keystone_env }}'
