---

# with module:
# neutron router-create <EDGE_ROUTER_NAME>
# neutron router-interface-add <EDGE_ROUTER_ID> <EXT_SUBNET_ID>
- name: Set keystone environment
  set_fact:
    keystone_env:
     OS_USERNAME: '{{ midonet_gateway_keystone_username }}'
     OS_TENANT_NAME: '{{ midonet_gateway_keystone_project }}'
     OS_PASSWORD:  '{{ midonet_gateway_keystone_password }}'
     OS_AUTH_URL: 'http://{{ midonet_gateway_keystone_hostname }}:{{ midonet_gateway_keystone_port }}/v3'
     OS_PROJECT_DOMAIN_NAME: '{{ midonet_gateway_keystone_project_domain_name }}'
     OS_USER_DOMAIN_NAME: '{{ midonet_gateway_keystone_user_domain_name }}'

- name: Create edge router with external interface
  os_router:
    state: present
    name: '{{ midonet_gateway_edge_router_name }}'
    network: '{{ midonet_gateway_external_network_name }}'
  environment: '{{ keystone_env }}'

- name: Grab networks
  command: neutron net-list
  register: net_list
  changed_when: False
  environment: '{{ keystone_env }}'

- name: Create edge network
  command: neutron net-create {{ midonet_gateway_edge_network_name }} --tenant_id {{ midonet_gateway_keystone_project }} --provider:network_type uplink
  when: '"{{ midonet_gateway_edge_network_name }}" not in net_list.stdout'
  environment: '{{ keystone_env }}'

- name: Create edge subnet
  os_subnet:
    name: '{{ midonet_gateway_edge_subnet_name }}'
    state: present
    network_name: '{{ midonet_gateway_edge_network_name  }}'
    cidr: '{{ midonet_gateway_veth_network }}'
    enable_dhcp: False
  environment: '{{ keystone_env }}'

- name: Grab ports
  command: neutron port-list
  register: port_list
  changed_when: False
  environment: '{{ keystone_env }}'

- name: Create uplink port
  command: >
    neutron port-create "{{ midonet_gateway_edge_network_name }}" --binding:host_id
    "{{ ansible_hostname }}" --binding:profile type=dict
    interface_name="{{ midonet_gateway_external_nic }}" --fixed-ip ip_address="{{ midonet_gateway_veth1_ip  | ipaddr('address') }}"
    --name "{{ midonet_gateway_edge_port_name }}"
  register: create_uplink_port
  environment: '{{ keystone_env }}'

- name: Add interface to router
  command: neutron router-interface-add {{ midonet_gateway_edge_router_name }} port={{ midonet_gateway_edge_port_name }}
  when: create_uplink_port.changed
  environment: '{{ keystone_env }}'
