---

- meta: flush_handlers
- include: packages_redhat.yml
  when: ansible_os_family == 'RedHat'
- include: packages_debian.yml
  when: ansible_os_family == 'Debian'
- include: keystone.yml
- include: external-network.yml
  when: midonet_gateway_create_external_network
- include: edge-router.yml
- include: bgp.yml
  when: midonet_gateway_bgp
- include: static_uplink.yml
  when: not midonet_gateway_bgp
